# Generated by Django 5.2.7 on 2025-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='ユーザーID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('color', models.CharField(choices=[('blue', '面接 (青)'), ('green', '説明会 (緑)'), ('red', '自己分析 (赤)'), ('yellow', 'その他 (黄)')], default='blue', max_length=10)),
            ],
            options={
                'verbose_name': 'カレンダーイベント',
                'verbose_name_plural': 'カレンダーイベント',
                'db_table': 'calendar',
                'ordering': ['start_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='プロンプト名')),
                ('content', models.TextField(verbose_name='プロンプト内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': 'プロンプト',
                'verbose_name_plural': 'プロンプト',
            },
        ),
    ]
